"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / '.env')

# Expose la doc API (Swagger/ReDoc) même hors DEBUG si explicitement activé
# (ex. environnement de recette). Jamais activé par défaut en production.
ENABLE_API_DOCS = env.bool('ENABLE_API_DOCS', default=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-v$kvr(!o2p#rqekek_qbq+jzariexi2q+ohh*n^gu^si79hj-p')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    # `jazzmin` doit précéder `django.contrib.admin` : il surcharge les
    # templates admin, l'ordre conditionne la résolution des templates.
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'django_filters',
    'apps.core',
    'apps.identite',
    'apps.reservations',
    'apps.paiements',
]

AUTH_USER_MODEL = 'identite.Utilisateur'

# `infrastructure/` (ou `models.py` direct pour les contextes support)
# regroupe tout le code d'accès aux données de chaque app, au lieu du
# `migrations/` à la racine de l'app attendu par convention Django.
MIGRATION_MODULES = {
    'reservations': 'apps.reservations.infrastructure.migrations',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.middleware.AuditContextMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# PostgreSQL est requis (pas SQLite) : la contrainte d'exclusion GiST
# anti-chevauchement n'existe pas sur SQLite.
#
# Une seule base PostgreSQL partagée par tous les contextes (identite,
# reservations, paiements), schéma `public` unique, FKs inter-contextes
# autorisées (ex. Reservation.membre -> identite.Membre).

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='systeme_reservation_db'),
        'USER': env('DB_USER', default='adem'),
        'PASSWORD': env('DB_PASSWORD', default='123456'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'EXCEPTION_HANDLER': 'apps.reservations.interfaces.api.views.reservation_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular : génération du schéma OpenAPI + Swagger UI / ReDoc servis
# en local via le sidecar (pas de CDN, cf. `drf_spectacular_sidecar` dans
# INSTALLED_APPS). `SCHEMA_PATH_PREFIX` et `TAGS` reflètent les routes
# réellement montées dans `config/urls.py` / `apps/*/interfaces/api/urls.py`.
SPECTACULAR_SETTINGS = {
    'TITLE': "API — Système de Réservation d'Espaces de Coworking",
    'DESCRIPTION': (
        "API du backend de réservation de salles de coworking, structuré en "
        "Domain-Driven Design (contexte cœur `reservations`, contextes support "
        "`identite` et `paiements`). Système strictement privé : tous les "
        "endpoints nécessitent une authentification JWT (Bearer), il n'existe "
        "aucun accès visiteur/anonyme."
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': True,
    'SCHEMA_PATH_PREFIX': r'/api/v2/',
    # Assets Swagger UI / ReDoc servis localement (sidecar), aucune requête CDN.
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'filter': True,
    },
    'TAGS': [
        {'name': 'Authentification', 'description': "Connexion, rafraîchissement et révocation des tokens JWT (`auth/login`, `auth/refresh`, `auth/logout`, `auth/me`)."},
        {'name': 'Membres', 'description': "Gestion des membres (`membres/`, réservée aux gestionnaires)."},
        {'name': 'Gestionnaires', 'description': "Gestion des comptes gestionnaires (`gestionnaires/`)."},
        {'name': 'Salles', 'description': "Catalogue des salles de coworking (`salles/`, `salles/disponibles/`)."},
        {'name': 'Créneaux', 'description': "Créneaux réservables rattachés à une salle (`creneaux/`)."},
        {'name': 'Réservations', 'description': "Cycle de vie des réservations : création, confirmation, annulation (`reservations/`)."},
        {'name': 'KPIs', 'description': "Indicateurs de pilotage : occupation, revenu, tableau de bord (`kpis/occupation`, `kpis/revenu`, `kpis/dashboard`), réservés aux gestionnaires."},
        {'name': 'Paiements', 'description': "Déclenchement et consultation des paiements (`paiements/`)."},
    ],
    # Pas de multi-service réel dans ce backend (une seule app Django,
    # une seule base Postgres partagée) : un seul serveur, l'URL de base
    # effective de `runserver` / du déploiement configuré.
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': "Développement local (`runserver`)"},
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=env.int('JWT_ACCESS_MINUTES', default=30)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env.int('JWT_REFRESH_DAYS', default=7)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
}

# django-jazzmin : thème de l'admin Django. Modèles/icônes énumérés à partir
# des enregistrements réels dans apps/*/admin.py et
# apps/reservations/interfaces/admin.py — pas de modèle inventé.
JAZZMIN_SETTINGS = {
    'site_title': 'Coworking Admin',
    'site_header': 'Réservation Coworking',
    'site_brand': 'Coworking Résa',  # <= 19 caractères
    'welcome_sign': "Bienvenue sur l'administration du système de réservation de coworking",
    'copyright': 'Système de Réservation de Coworking',
    'search_model': ['identite.Utilisateur', 'identite.Membre'],
    'topmenu_links': [
        {'name': 'Accueil', 'url': 'admin:index'},
        {'name': 'Documentation API (Swagger)', 'url': 'api-docs', 'new_window': True},
        {'name': 'Documentation API (ReDoc)', 'url': 'api-redoc', 'new_window': True},
    ],
    'icons': {
        'auth.Group': 'fas fa-users',
        'identite.Utilisateur': 'fas fa-user-shield',
        'identite.Membre': 'fas fa-id-card',
        'identite.Gestionnaire': 'fas fa-user-tie',
        'reservations.EspaceCoworking': 'fas fa-door-open',
        'reservations.Reservation': 'fas fa-calendar-check',
        'paiements.Paiement': 'fas fa-credit-card',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    # Flux métier : identité -> réservations (salles/créneaux) -> paiements.
    'order_with_respect_to': ['identite', 'reservations', 'paiements'],
    'related_modal_active': True,
    'changeform_format': 'horizontal_tabs',
}

# Palette la plus proche des couleurs de marque (#2E4A7B / #C9A24B)
# atteignable avec les classes/thèmes fournis par django-jazzmin sans ajouter
# de CSS personnalisé (hors périmètre de cette tâche) : le thème bootswatch
# "sandstone" a le bleu primaire le plus proche de #2E4A7B parmi les thèmes
# embarqués, "accent-warning" (ambre) est l'équivalent le plus proche de l'or
# #C9A24B disponible nativement.
JAZZMIN_UI_TWEAKS = {
    'theme': 'sandstone',
    'navbar': 'navbar-dark',
    'navbar_small_text': False,
    'no_navbar_border': False,
    'brand_colour': 'navbar-primary',
    'accent': 'accent-warning',
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_flat_style': False,
    'default_theme_mode': 'auto',
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}
