# Generated by Django 6.0.6 on 2026-07-14 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_reservation_no_overlap_exclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_valeur', models.DecimalField(db_column='montant_valeur', decimal_places=2, max_digits=8)),
                ('_devise', models.CharField(db_column='montant_devise', default='TND', max_length=3)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=10)),
                ('moyen', models.CharField(choices=[('CARTE', 'Carte bancaire'), ('VIREMENT', 'Virement'), ('ESPECES', 'Espèces')], default='CARTE', max_length=10)),
                ('reference_externe', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='paiement', to='reservations.reservation')),
            ],
            options={
                'db_table': 'paiement',
                'constraints': [models.CheckConstraint(condition=models.Q(('_valeur__gt', 0)), name='paiement_montant_strictement_positif')],
            },
        ),
    ]
