# Generated by Django 6.0.6 on 2026-07-14 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspaceCoworking',
            fields=[
                ('id_espace', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_espace', models.CharField(choices=[('BUREAU_PRIVE', 'Bureau privé'), ('OPEN_SPACE', 'Open space'), ('SALLE_REUNION', 'Salle de réunion')], max_length=20)),
                ('capacite', models.IntegerField()),
                ('tarif_horaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('localisation', models.CharField(blank=True, max_length=150, null=True)),
                ('id_gestionnaire', models.UUIDField()),
                ('equipements', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'espace_coworking',
                'constraints': [models.CheckConstraint(condition=models.Q(('capacite__gt', 0)), name='espace_coworking_capacite_positive'), models.CheckConstraint(condition=models.Q(('tarif_horaire__gte', 0)), name='espace_coworking_tarif_horaire_non_negatif'), models.CheckConstraint(condition=models.Q(('type_espace__in', ['BUREAU_PRIVE', 'OPEN_SPACE', 'SALLE_REUNION'])), name='espace_coworking_type_espace_valide')],
            },
        ),
        migrations.CreateModel(
            name='CreneauSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Réservé')], default='DISPONIBLE', max_length=10)),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='reservations.espacecoworking')),
            ],
            options={
                'db_table': 'creneau',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creneau_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='reservations.creneauslot')),
                ('espace', models.ForeignKey(db_column='id_espace', on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='reservations.espacecoworking')),
                ('membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='identite.membre')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.AddConstraint(
            model_name='creneauslot',
            constraint=models.CheckConstraint(condition=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='creneau_heure_fin_apres_debut'),
        ),
        migrations.AddConstraint(
            model_name='creneauslot',
            constraint=models.UniqueConstraint(fields=('espace', 'date', 'heure_debut', 'heure_fin'), name='creneau_unique_par_salle'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='reservation_date_fin_apres_date_debut'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('montant_total__gte', 0)), name='reservation_montant_total_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('statut__in', ['EN_ATTENTE', 'CONFIRMEE', 'ANNULEE'])), name='reservation_statut_valide'),
        ),
    ]
