# Generated by Django 6.0.6 on 2026-07-14 11:38

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=10)),
                ('row_id', models.CharField(max_length=64)),
                ('acteur_id', models.BigIntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('donnees', models.JSONField()),
                ('horodatage', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['horodatage'], name='audit_log_horodatage_brin')],
            },
        ),
    ]
